MYSQL_HOST: "134.175.128.151"
MYSQL_PORT: 3306
MYSQL_USER: 'root'
MYSQL_PASSWORD: '3558hominT.'
MYSQL_DB: 'docteam'
MYSQL_CHARSET: 'utf8mb4'
SERVER_PORT: 8530
MaxConnections: 100
FILE_APP_HOST: http://127.0.0.1:8770
SHUTDOWN_PASSWORD: "closePassword"